FROM python:3.9-slim-buster
RUN apt update && apt upgrade -y \
	&& apt install -y cron \
	&& pip install \
		flask \
		flask_cors \
		waitress \
		pandas
EXPOSE 80
CMD bash -c "cd $APP_PATH && waitress-serve --port=80 --call $CALL"

